---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Aniruddha Gokhale
# Created: Fall 2017
# Modified: Fall 2020
#
# This playbook is our demo master file
# The goal is to show how to have a single master file which then
# includes multiple plays according to some well-designed choreography
#
# This file is similar to the one in the AnsibleOnly_Local_and_Cloud folder
# For now I just kept one play in here but feel free to add more.


#####################################################
### Play 1: Get facts from all our VMs
#
# Here I show the use of import_tasks from child playbooks
#####################################################
- name: "Play 1: Perform fact gathering on all VMs"
  hosts: all
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
    - ansible-base
 
 # specified in the MyInventory file
  remote_user: cc       # note that the user is ubuntu for 
                             # vagrant-created VM else use the
                             # appropriate user name

  
  gather_facts: yes          # We ask Ansible to collect all facts

  
  tasks:
    - include_tasks: tasks/cleanupCluster.yml
      when: inventory_hostname in groups['VM2']
      
      


...
