apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: volconnect
spec:
  type: LoadBalancer
  ports:
  - name: port1
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000
  - name: port2
    port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30001
  selector:
    app: volconnect
